FROM ruby:2.4.1

RUN apt-get update -qq && \
    apt-get install -y build-essential \
    libpq-dev \
    nodejs \
    telnet \
    bash \
    supervisor \
    vim \
    xterm \
    ca-certificates \
    unzip && \
    rm -rf /var/cache/apk/*

## Setup Rails

RUN gem install rails && rails new <%= @name %> <% if @database %>-d <%= @database %><% end %>
WORKDIR /<%= @name %>
ADD app/* /<%= @name %>/app

EXPOSE 3000

CMD /<%= @name %>/bin/rails s -b 0.0.0.0
